# Use the official torchserve:latest image as the base image
ARG BASE_IMAGE=pytorch/torchserve:latest-gpu
FROM ${BASE_IMAGE} AS compile-image

#Python version
ARG PYTHON_VERSION=3.10

# Install additional Python packages
RUN pip install soundfile

# Set the working directory
# WORKDIR "./serve"


